Do zrobienia :
- W feature elimination wypisać, ile features jest obecnie branych pod uwagę --gotowe
- W feature elimination wykazać, które z listy features są brane pod uwagę (obecnie wypisuje po prostu wszystkie feature_names) --gotowe?
- Zmienić wartości na % --gotowe
- Zmienić concinue na continue --gotowe
- W feature extraction jest problem z fft_sum - prawdopodobnie przekazanie fft_sum odbywa się źle (pojawia się błąd mówiący, że dla zmiennej jest 0 dimensions) Czy w tym wypadku próbowało by przyporządkować na raz dwie wartości z racji podwójnego wykonania się pętli?
--gotowe




- Błąd w pisowni dla uruchomienia funkcji feature extraction --gotowe
- Stworzyć w końcu to FFT dla argmaxa
- Dodać linię przerwy pomiędzy poszczególnymi testami w RSE --gotowe





- jest problem z fft - trzeba prawdopodobnie wykluczyć składowe mniejsze od 0


- num_chunks = extracted_data.shape[0]//chunk_size - tutaj właściwie trzeba wywalić chunk size, bo jest raczej zbędne
shape[0] oddaje raczej obserwacje









-- używać po jednym pliku z pętlą 


Labeling
-- nie trzeba dawać shape, można zmienić potem gdy jest już numpyy array

- window size jako argument, nie w funkcji 
- może zmienić na dane z 5 sekund

-zapisywać segmentację



Feature extraction
multi dimensional array indexing
--(i,:,j)


dx1 = np.logical_and(sensor_1_freq >= 0, sensor_1_freq <= freq)


Plot power spectrum!


subject dependent and independent classification










/home/marekjedrychowski/LubeckMasterThesis/FeatureExtraction.py:29: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  kurtosis_array[i] = scipy.stats.kurtosis(data[i], axis=0)
/home/marekjedrychowski/LubeckMasterThesis/FeatureExtraction.py:30: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  skewness_array[i] = scipy.stats.skew(data[i], axis=0)









Number of features selected: 16
Traceback (most recent call last):
  File "c:\Users\janja\LubeckMasterThesis\Main.py", line 61, in <module>
    feature_elimination_loop(num_features, shuffled_dir, feature_names, feature_description_folder)
  File "c:\Users\janja\LubeckMasterThesis\FeatureSelection.py", line 86, in feature_elimination_loop
    statistics = feature_elimination(i, shuffled_dir, feature_names)
  File "c:\Users\janja\LubeckMasterThesis\FeatureSelection.py", line 41, in feature_elimination
    names_selected_features.append(feature_names[i])
IndexError: list index out of range